apiVersion: v2
name: silly-webapp
description: A simple web application exposing credentials retrieved from a Vault instance through the External Secrets Operator (ESO).
type: application
version: 0.1.0
appVersion: "2.4"
