apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: webindex
  namespace: silly-webapp
spec:
  #refreshInterval: 1h
  secretStoreRef:
    kind: SecretStore
    name: vault
  target:
    name: webindex
    template:
      engineVersion: v2
      data:
        index.html: |
          <table border=1 style="background-color:{{ .BGCOLOR }};color:{{ .COLOR }}"
            <tr>
              <th>SECRET</th>
              <th>VALUE</th>
            </tr>
            <tr>
              <td>BGCOLOR</td>
              <td>{{ .BGCOLOR }}</td>
            </tr>
            <tr>
              <td>COLOR</td>
              <td>{{ .COLOR }}</td>
            </tr>
            <tr>
              <td>LOGIN</td>
              <td>{{ .LOGIN }}</td>
            </tr>
            <tr>
              <td>PASSWORD</td>
              <td>{{ .PASSWORD }}</td>
            <tr>
          </table>

  data:
  - secretKey: BGCOLOR
    remoteRef:
      key: silly-webapp
      property: BGCOLOR
  - secretKey: COLOR
    remoteRef:
      key: silly-webapp
      property: COLOR
  - secretKey: LOGIN
    remoteRef:
      key: silly-webapp
      property: LOGIN
  - secretKey: PASSWORD
    remoteRef:
      key: silly-webapp
      property: PASSWORD

