apiVersion: external-secrets.io/v1beta1
kind: SecretStore
metadata:
  name: vault
  namespace: silly-webapp
spec:
  provider:
    vault:
      server: "http://vault.vault:8200"
      namespace: silly-webapp
      path: "kv"
      version: "v2"
      auth:
        kubernetes:
          mountPath: kubernetes
          role: silly-webapp
          serviceAccountRef:
            name: silly-webapp

