---
apiVersion: v1
kind: Service
metadata:
  name: silly-webapp
  namespace: silly-webapp
  labels:
    app: silly-webapp
spec:
  type: NodePort
  ports:
    - port: 80
      targetPort: 80
      protocol: TCP
      name: httpd
  selector:
    app: silly-webapp
