apiVersion: external-secrets.io/v1beta1
kind: SecretStore
metadata:
  name: vault
  namespace: {{ .Release.Name }}
spec:
  provider:
    vault:
      server: "http://{{ .Values.vault.namespace }}.{{ .Values.vault.service.name }}:{{ .Values.vault.service.port }}"
      namespace: {{ .Release.Name }}
      path: "kv"
      version: "v2"
      auth:
        kubernetes:
          mountPath: kubernetes
          role: {{ .Release.Name }}
          serviceAccountRef:
            name: {{ .Release.Name }}
