apiVersion: v1
kind: Service
metadata:
  name: prometheus
  namespace: monitoring
spec:
  selector: 
    app: prometheus
  type: NodePort  
  ports:
    - targetPort: 9090
      port: 9090
      nodePort: 30090