apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: prometheus-logs
  namespace: monitoring
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: standard
  volumeName: prometheus-logs